name: Share Link

on:
  schedule:
    - cron: '0 * * * *' # Exécute chaque heure

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send update
        run: |
          curl -X POST https://api.your-service.com/share \
          -H "Authorization: Bearer YOUR_API_KEY" \
          -d '{"link": "YOUR_SHORTENED_LINK"}'
